global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['192.168.1.57:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.57:9100']

  - job_name: 'node1'
    static_configs:
      - targets: ['192.168.1.80:9100']

#  - job_name: 'mysql'
#    scrape_interval: 1m
#    static_configs:
#      - targets: ['192.168.1.80:9104']
  - job_name: 'mysql' # To get metrics about the mysql exporter’s targets
    params:
      # Not required. Will match value to child in config file. Default value is `client`.
      auth_module: [client.servers]
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - 192.168.1.80:3306
        #- server2:3306
        #- unix:///run/mysqld/mysqld.sock
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: 192.168.1.80:9104

  - job_name: 'blackbox-http_2xx-general'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx-general] # наш модуль из blackbox.yml
    static_configs:
      - targets:
        - https://192.168.1.200 # что мониторим
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.57:9115 # адрес сервиса blackbox

remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'
