version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager-data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:latest
    # privileged: true
    restart: unless-stopped
    container_name: blackbox
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    networks:
      - monitoring

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
#      - ./grafana/provisioning/dashboards/provisioning-dashboards.yml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yml:ro
#      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasourses/datasource.yml:ro
      - grafana_data:/var/lib/grafana
#      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning:/etc/grafana/provisioning/
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
#      - ./grafana/provisioning/dashboards/1860_rev37.json:/var/lib/grafana/provisioning/dashboards/1860_rev37.json:ro
#      - ./grafana/provisioning/dashboards/13659_rev1.json:/var/lib/grafana/provisioning/dashboards/13659_rev1.json:ro
#      - ./grafana/provisioning/dashboards/blackbox.json:/var/lib/grafana/provisioning/dashboards/blackbox.json:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
