version: '3.3'
services:
  telegraf:
    image: telegraf:1.26-alpine
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    restart: always
    container_name: telegraf
    hostname: telegraf
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - default

  influxdb:
    image: influxdb:1.8-alpine
    restart: always
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - ./volumes/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volumes/influxdb:/var/lib/influxdb:rw
    networks:
      default:
        aliases:
         - influxdb

  chronograf:
    image: chronograf:1.8-alpine
    restart: always
    container_name: chronograf
    hostname: chronograf
    ports:
      - 8888:8888
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - chronograf

  kapacitor:
    image: kapacitor:1.7-alpine
    restart: always
    container_name: kapacitor
    hostname: kapacitor
    ports:
      - 9092:9092
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: "http://influxdb:8086"
      KAPACITOR_INFLUXDB_ENABLED: "true"
      KAPACITOR_HTTP_AUTH_ENABLED: "true"
      KAPACITOR_INFLUXDB_0_USERNAME: admin
      KAPACITOR_INFLUXDB_0_PASSWORD: password
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    networks:
      default:
        aliases:
         - kapacitor
