apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: "postgres"
    secure_json_data:
      password: postgres
    database: "test"
    version: 1
    editable: true
    json_data:
      sslmode: "disable"
